version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install awscli
      - curl -LO https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      - unzip terraform_1.8.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform --version
      - terraform init
  build:
    commands:
      - terraform apply -auto-approve
artifacts:
  files:
    - '**/*'
