version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
    
  pre_build:
    commands:
      - terraform --version
      - terraform init
  build:
    commands:
      - terraform apply -auto-approve
artifacts:
  files:
    - '**/*'
